version: "3.2"

services:
  redis:
    image: redis:5.0
    ports:
      - "6379:6379"

  mongodb:
    image: mongo:4.2-bionic
    ports:
      - "27017:27017"

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'demo'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'

  myapp:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      GIN_MODE: "debug"           # Gin mode: debug | release
      REPOSITORY_TYPE: "inmemory" # Repository type: inmemory | mongodb | mysql | redis
      REDIS_URI: "redis:6379"
      MONGODB_URI: "mongodb://mongodb:27017/demo"
      MYSQL_CONNECTION_STRING: "user:password@tcp(mysql:3306)/demo?parseTime=true"
    depends_on:
      - redis
      - mongodb
      - mysql
    working_dir: /app
    command: bash -c "go test ./... && go run main.go"