version: "3.2"

services:
  redis:
    image: redis:5.0
    ports:
      - "6379:6379"

  mongodb:
    image: mongo:4.2-bionic
    ports:
      - "27017:27017"

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'demo'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'

  myapp:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - mongodb
      - mysql